name: Check that an issue is linked to this pull request.
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    steps:
      - uses: nearform/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          github-token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          exclude-branches: "dependabot/**"
          comment: false

      - name: Get the output
        run: echo "How many linked issues? ${{ steps.check-linked-issues.outputs.linked_issues_count }}"