name: Create a link to template on master
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
    branches:
      - master

jobs:
  check_for_notebook:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Create Output folder
        run: | 
            mkdir -p output/

      - name: Get file changes in commit
        id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: List files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "File: ${changed_file}."
            echo "file_name=${changed_file}" >> $GITHUB_ENV
            echo contains(${changed_file}, ".ipynb")

            if [[$changed_file == *".ipynb."*]]; then
              echo "found .ipynb"
            fi
          done

      - name: Check for .ipynb
        if: contains( ${{ steps.files.outputs.added }}, ".ipynb" ) 
        run: |
          echo "The template is now available on the master branch on this link: 
          https://github.com/${{ github.event.pull_request.head.repo.full_name }}/blob/master/${changed_file}
          
          "
          echo "Contains a .ipynb file"
        