name: Create a link to template on master
on:
  pull_request:
    types:
      - closed
      - open
    branches:
      - master

jobs:
  check_for_notebook:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check for notebook in commit
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done