name: Create a link to template on master
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
    branches:
      - master

jobs:
  check_for_notebook:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get file changes in commit
        id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: List files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "File: ${changed_file}."
          done
      - name: Check for .ipynb
        if: contains( ${{ steps.files.outputs.all }}, ".ipynb" ) 
        run: echo "Contains a .ipynb file"
  
  Call_for_API:
    runs-on: ubuntu-latest
    steps:
      - name: Make request to get details
        uses: satak/webrequest-action@master
        id: webhook
        # replace url with your organization's name if needed
        with:
          url: https://api.github.com/repos/${{ github.event.pull_request.head.repo.full_name }}/pulls/${{ github.event.pull_request.number }}/files
          method: GET
      
      - name: show result
        run: |
          for changed_files in ${{ steps.webhook.outputs.output) }}; do
            echo "File: ${changed_files}."
          done
        #  echo ${{ fromJson(steps.webhook.outputs.output).data }}

