name: Create a link to template on master
on:
  pull_request:
    types:
      - closed
      
    branches:
      - master

jobs:
  check_for_notebook:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Create Output folder
        run: | 
            mkdir -p output/

      - name: Get file changes in commit
        id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: List files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "File: ${changed_file}."
            if [[ "${changed_file}" == *".ipynb"* ]]; then

              echo ".IPYNB File detected"
              echo "The template is now available on the master branch on this link: 
              https://github.com/${{ github.event.pull_request.head.repo.full_name }}/blob/master/${changed_file}
              " > output/comment.md
            else
              echo "not there"
            fi
          done
        
      - uses: actions/upload-artifact@v1
        with:
          name: results
          path: output

      - uses: actions/download-artifact@v1
        with:
          name: results
      

      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/comment.md
        