name: Create a link to template on master
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
    branches:
      - master

jobs:
  check_for_notebook:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check for notebook in commit
        id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
  
  Call_for_API:
    runs-on: ubuntu-latest
    steps:
      - name: Make request to get details
        uses: satak/webrequest-action@master
        id: webhook
        # replace url with your organization's name if needed
        with:
          url: https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files
          method: GET
      
      - name: show result
        run: |
          for changed_files in ${{ fromJson(steps.webhook.outputs.output).data }}; do
            echo "Do something with thhis ${changed_files}."
          done
        #  echo ${{ fromJson(steps.webhook.outputs.output).data }}

