name: Create a link to template on master
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
    branches:
      - master

jobs:
  check_for_notebook:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get file changes in commit
        id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: List files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "File: ${changed_file}."
          done
      - name: Check for .ipynb
        if: contains( ${{ steps.files.outputs.added }}, ".ipynb" ) 
        run: echo "Contains a .ipynb file"
  