name: Generate Certificate when PR merged
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  generate_certificate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
    
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Get required variables
        env: 
          pr_name: ${{ github.event.pull_request.title }}
          org_profile_url: ${{ github.event.repository.url }}
          
      - name: Execute Test Script
      - run: "pip install PIL"
      - run: "pip install requests"
      - run: "pip install io"
      - run: "pip install bs4"
      - run: |
            echo "Store: $pr_name"
            
            python3 generate_certificate.py

  comment_pr:
    name: PR comment
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p output/
      - run: |
            echo "Thank you for your contribution @${{ github.event.pull_request.user.login }}, your PR has been merged into the master branch of awesome-notebook.
            Here is the contribution certificate you can share on social media so everybody knows how awesome you are :call_me_hand::earth_americas:.
            Spread the #opensource love  :green_heart:" > output/results.md
      - uses: actions/upload-artifact@v1
        with:
          name: results
          path: output
      - uses: actions/download-artifact@v1
        with:
          name: results
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/results.md
