name: Generate Certificate when PR merged
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  generate_certificate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Get required variables And run script
        env: 
          pr_name: ${{ github.event.pull_request.title }}
          org_profile_url: ${{ github.event.pull_request.head.user.html_url }}
          repo_name: ${{ github.event.repository.name }}
          contributor_name: ${{ github.actor }} 
          issue_title: ${{ github.event.pull_request.head.ref }}
          date: ${{ github.event.pull_request.created_at }}
          logo_url: ${{github.event.pull_request.head.user.avatar_url}}
        run: |
            pip install bs4
            pip install requests
            pip install pillow
            echo "##########################"
            echo "Store: $pr_name"
            echo "Org URL: $org_profile_url"
            echo "repo_name: $repo_name"
            echo "contributor: $contributor_name"
            echo "user_name: $user_name"
            echo "issue_title: $issue_title"
            echo "date: $date"
            echo "logo_url: $logo_url"
            
            echo "##########################"
            python3 generate_certificate.py
            
      - name: Commit files
        id: commit
        run: |
              git config --local user.email "action@github.com"
              git config --local user.name "github-actions"
              git add --all
              if [-z "$(git status --porcelain)"]; then
                echo "::set-output name=push::false"
              else
                git commit -m "Add certificate" -a
                echo "::set-output name=push::true"
              fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
  # comment_pr:
  #   name: PR comment
  #   if: github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Create Output folder and copy image
  #       run: | 
  #           mkdir -p output/
  #           cp certificate.png output/
  #     - run: |
  #           echo "Thank you for your contribution @${{ github.event.pull_request.user.login }}, your PR has been merged into the master branch of awesome-notebook.
  #           Here is the contribution certificate you can share on social media so everybody knows how awesome you are :call_me_hand::earth_americas:.
  #           Spread the #opensource love  :green_heart:

  #           ![Certificate](certificate.png) " > output/results.md
      
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: results
  #         path: output

  #     - uses: actions/download-artifact@v1
  #       with:
  #         name: results
      

  #     - name: comment PR
  #       uses: machine-learning-apps/pr-comment@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         path: results/results.md

  pr_comment:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Create Output folder and copy image
        run: | 
            mkdir -p output/
            cp certificate.png output/

      - uses: actions/checkout@v2

      - name: Comment in PR section
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Thank you for your contribution @${{ github.event.pull_request.user.login }}, your PR has been merged into the master branch of awesome-notebook.
            Here is the contribution certificate you can share on social media so everybody knows how awesome you are :call_me_hand::earth_americas:.
            Spread the #opensource love  :green_heart:![certificate](certificate.png)" > report.md
          
          cml-publish certificate.png --md >> report.md

          cml-send-comment report.md
        
      - uses: actions/upload-artifact@v1
        with:
          name: results
          path: output

      - uses: actions/download-artifact@v1
        with:
          name: results
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/results.md